### ISSUE TITLE
messy code when text with emoji.

### ISSUE THREAD

**Issue by TongchengQiu** [jrainlau/motto#1]
when then `lyric` of `option`  with emoji, the show text will bring messy code.
example:

```
var motto = new Motto('.title', {
  lyric: 'Hello, MottoJS! 😄',
  showUpSpeed: 120,
  flashSpeed: 100,
  flashTimeout: 1000,
  callback: function () {
    // do something...
  }
})
```

**Comment by jrainlau** [comment]
yes, because `emoji` wasn't support by browser itself, you should use some pollyfill to make it work, such as https://github.com/coocy/emoji and so on
